### ISSUE TITLE
Mostly works except for json error? Help Wanted

### ISSUE THREAD

**Issue by hykgoml** [n0bel/PiClock#102]
I have double checked the API key, in fact left it exposed below.  What I can't figure out is why I getting the error.  Used a Jessie install to match the doccumented "install guide". There are no hardware devices added at this time (temp, lights, IR).  Just trying to get it to tell the weather first.
Linux raspberrypi 4.9.35+ #1014 Fri Jun 30 14:34:49 BST 2017 armv6l GNU/Linux
tried as pi and as root
What other info can I give besides error message?

getting current and forecast:Fri Apr 20 09:45:16 2018
http://api.wunderground.com/api/da8b15f3a16b6420/conditions/astronomy/hourly10day/forecast10day/lang:EN/q/44.070521,-122.98417.json?r=0.854280859017
wxstart for radar1
get radar api call spacing oneshot get i=0.1
wxstart for radar2
get radar api call spacing oneshot get i=1.94017791748
Traceback (most recent call last):
  File "PyQtPiClock.py", line 173, in wxfinished
    wxdata = json.loads(wxstr)
  File "/usr/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 366, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 384, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by n0bel** [comment]
closed as resolved or no longer needed (old)
