### ISSUE TITLE
Obtaining Weather Information from PWS?

### ISSUE THREAD

**Issue by KE8AFF** [n0bel/PiClock#104]
Not that its gonna matter much longer as wunderground is no longer offering free access to their api, would there happed to be a way to get the PiClock to grab the info from my own personal weather station? I would imagine that it would be somewhere in the api but i have no clue how to do it.

**Comment by hsoj95** [comment]
I mean, I guess in theory you could pull the info directly from your own station, build a JSON/XML file from that, and then alter the Python code to read from that JSON/XML file on a local server. Not exactly an easy process though, especially since every station is different
