### ISSUE TITLE
Having trouble with lirc - unable to configure rc device

### ISSUE THREAD

**Issue by Charlie-Habekost** [n0bel/PiClock#107]
Using latest Raspian, Linux 4.14.34-v7+ armv7l Tried to get lirc working. Can see data with mode2. No output with irw. Using status of lircd service as below. Seems to be ambiguity from lirc and new lircd?
Have set up as in the guide.
Really perplexed. /etc/lirc/hardware.conf has DEVICE="/dev/lirc0".
Running systemctl status lircd.service shows:
Info: Cannot configure the rc device for /dev/lirc
Nov 11 17:39:38 PiClock lircd-0.9.4c[441]: Error: could not get file information for /dev/lirc
Nov 11 17:39:38 PiClock lircd-0.9.4c[441]: default_init(): No such file or directory

Any ideas???

Thanks!

**Comment by n0bel** [comment]
lirc issues  dealt with in the new instructions.
