### ISSUE TITLE
The weather forecast DarkSky does not work at a latitude of over 67 degrees

### ISSUE THREAD

**Issue by xenon462** [n0bel/PiClock#118]
The weather forecast DarkSky does not work at a latitude of over 67 degrees
Kugaaruk, NU, Canada
68.538063, -89.790116

Grønnegata 57-67, 9008 Tromsø, Norway
69.649215, 18.954063

Murmansk Russia 
68.956876, 33.074742

Airport Way, Prudhoe Bay, AK 99734
70.197213, -148.461031

There is no sunriseTime, sunsetTime parameter in the json file from darksky.
Now in the northern latitudes polar night. 
The sun does not appear over the horizon.
Parameters sunriseTime, sunsetTime are used in the PyQtPiClock.py file line 286 and 289.
How to fix it?

**Comment by n0bel** [comment]
Fixed as of https://github.com/n0bel/PiClock/commit/ef2ba9a62581d702e537c6da58c17a1364cc3723
