### ISSUE TITLE
USB Sound card's for NOAA radio

### ISSUE THREAD

**Issue by Commander-Crash** [n0bel/PiClock#123]
No issue but This is just a option for others just in case they have a USB sound card connected to their Pi and had issues getting mpg123 to play noaa radio. If you wish to change "mpg123" to say "omxplayer" then all you have to do is "cd" PiClock/Clock and vi or nano "PyQtPiClock.py" look for " weatherplayer = Popen("  on the next line change to

["omxplayer", "-o", "alsa:hw:1,0", Config.noaastream]

So it will look like 

                    if weatherplayer is None:
                        weatherplayer = Popen(
                            ["omxplayer", "-o", "alsa:hw:1,0", Config.noaastream])

Save and close and their you go.
Be sure to make a backup before edit of PyQtPiClock.py

**Comment by n0bel** [comment]
I might add a config variable for it.
