### ISSUE TITLE
Weather forecast units is hardcoded 'us'

### ISSUE THREAD

**Issue by BertLindeman** [n0bel/PiClock#124]
Maybe 'auto' would be the easiest choice for units in def getwx().
```
    wxurl += str(Config.location.lat) + ',' + \
        str(Config.location.lng)
    wxurl += '?units=auto&lang=' + Config.Language.lower() # /BL hardcoded units, maybe auto easier than us?
```
For me it resulted in a forecast with snow height in inches. Would like mm or even cm ;-)

**Comment by BertLindeman** [comment]
There are conversions in PyQtPiClock that produce curious results if I use auto for the units ;-)
Currently the temperature in about minus 1.3 Celsius and "converted from Fahrenheit into Celsius"
So I was thinking a bit too easy about this. Picture with the wrong values ;-)

![image](https://user-images.githubusercontent.com/8142081/51415825-7a64df00-1b77-11e9-9456-410213c22d73.png)

Minus 20 Celsius is here very rare, for @xenon462 it is more common ;-)

**Comment by xenon462** [comment]
I removed the multiplication by the coefficient. Everything is working fine for me.
![7](https://user-images.githubusercontent.com/34947093/51416407-7bebd280-1b8a-11e9-80e7-b2cd4c21c1fa.png)

**Comment by BertLindeman** [comment]
Ah, so not so difficult, but to generalize it sti;; takes some programming the conversion depending  on the units variable. Thank you for the update.
