### ISSUE TITLE
Text layout issues.

### ISSUE THREAD

**Issue by ScottChapman** [n0bel/PiClock#125]
(I thought there was an issue on this, but couldn't find it...)

I frequently have text overlap issues when the weather gets complicated (see included picture).
![img_20181230_153137](https://user-images.githubusercontent.com/1517892/51441305-328ca780-1c9e-11e9-988d-f19d1dcaa880.jpg)

I was thinking of ways to give more space to the forecast text; maybe:
```
-------------------------------------------------------
|     Icon   |               10% rain 35/24 F  |
|   Date    |                                            |
| - - - - - - - - - - - - - - - - - - - - - - - - - - -  |
|   forecast text                                     |
-------------------------------------------------------
```
or maybe:
```
-------------------------------------------------------
|  Date        10% rain 35/24F                |
| - - - - - - - - - - - - - - - - - - - - - - - - - - -  |
|   Icon  | forecast text                          |
|   Icon  | forecast text                          |
|   Icon  | forecast text                          |
-------------------------------------------------------
```

Dunno, the text is pretty useful, gotta think there is some reasonable layout that makes it less likely that there would be overlap (and maybe just truncate then).

(sorry for the crappy layout examples, but I think you get the idea...)

**Comment by BertLindeman** [comment]
Hi Scott, do you mean  "Day forecast test truncation"  #108 Maybe you did not find it because it's closed?

**Comment by ScottChapman** [comment]
Oh yea, not sure how I missed that (I did a bunch of queries including closed ones), but yea that's the one.

It is an issue (even if there is no obvious fix), at least for me. very week there seems like there is at least one day that has some serious overlap/truncation issue. Maybe keep this one open since I like the layouts here better than the one in #108 

I just think they key is to give the forecast more space even if that means giving it a smaller font. I do realize the is no (obvious) way to avoid it, but surely we could make it happen less frequently?

Is this not an issue for anyone else?

**Comment by BertLindeman** [comment]
I agree that the current text layout is (much) better than before #108 
And yes overlap occurs from time to time:

![image](https://user-images.githubusercontent.com/8142081/51442218-f297e580-1cda-11e9-8e4b-4ed4053b5a25.png)

Blown-up like this it's even almost readible ;-)

I do **not** think that a variable fontsize depending on the contents is the solution. It might be ugly.

**Comment by ScottChapman** [comment]
;-)

But yea, I agree that having different font sizes for the same features would not be great. Though I suppose it would be possible to do it per-display (meaning perhaps a smaller font is used for all the forecasts if any day be too long). But I'm not enamored with that idea either.

Just spit-ballin'. Trying to find something relatively simple and not too sucky...

**Comment by ScottChapman** [comment]
I did't think of overlaying. I could try to mock up a better example of each. I guess I could try to mock it up in google slides to give the opportunity to mess around with it.

**Comment by BertLindeman** [comment]
Interesting!
But there's always the thing to get it programmed ;-)

**Comment by xenon462** [comment]
here is my decision.
need to change date format.
![9](https://user-images.githubusercontent.com/34947093/51454508-1c422280-1d56-11e9-8c8b-3ffd70a520c0.png)
you need to align the date on the left. The text needs to be aligned to the right.
![10](https://user-images.githubusercontent.com/34947093/51454677-fec18880-1d56-11e9-80c4-2c96d7f58ffa.png)
![2019-01-21-083711_1280x1024_scrot](https://user-images.githubusercontent.com/34947093/51454858-f027a100-1d57-11e9-845f-8d4307e7908b.png)

**Comment by feh123** [comment]
The arial idea is very good - that separates my weather text really well. I do like the pale background and the dark text/clock. How do you alter these colours - currently I just take the default settings? Thanks.

**Comment by BertLindeman** [comment]
@feh123 It's not really difficult.
I assume that you installed in the default location: `/home/pi/PiClock/Clock/`

The settings used by default are in the file Config.py
Save a copy and step by step update your Config.py

Look in /home/pi/PiClock/Clock/images for the images you like best.

In my Config.py (part of them):
```
squares1 = 'images/squares1-jean.png'
squares2 = 'images/squares2-jean.png'
textcolor = '#000040'
textfont = 'arial' # was 'sans-serif'
clockface = 'images/clockface3-darkblue.png'
hourhand = 'images/hourhand-darkblue.png'
minhand = 'images/minhand-darkblue.png'
sechand = 'images/sechand-darkblue.png'

background = 'images/myclockbackground.jpg'
```
Create a picture / drawing you like or crawl the web to find a nice picture. 
and place it in the images directory.
Update your Config.py and restart the clock.
And if you are happy show us ;-)

**Comment by BertLindeman** [comment]
Yes I see on startup of the clock:
```
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
```
I did not bother to get rid of it, as you saw in a previous post.
Many items on the net state: "ignore".
Like (an older post) [on Stackoverflow](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile#22747902)

But you say you (only?) get a black background.
Do you see any other errors in your log?

**Comment by BertLindeman** [comment]
Hmm, Probably not the case, but just incase (assuming you use user `pi`):
- no UpperCase / lowerCase issue in the filename / path / Config-text 
- pi is the owner of the jpg/png
- has read/execute access


That it **is** a valid jpg/png you already tested by looking at it.
Coming at the end of my options ;-( 

Would it be possible copy the image or drop a link to it here, so I could try it?
(Think about copyright)

**Comment by feh123** [comment]
![cold-snow-white-605615](https://user-images.githubusercontent.com/31826354/51535076-605d2200-1e3f-11e9-94da-8c50dbb04b1d.jpg)

Cannot see any errors - permissions set in VNC and seem okay. Seem to be able to add all current images already in Clock/image folder without issue. No copyright. Hope this drag/drop works! Thanks for the help!

**Comment by BertLindeman** [comment]
Saved the image local as `cold-snow-white.jpg` 
made pi owner
took my Config.py and made Config-snow.py
Only changed 
```background = 'images/clockbackground-kevin.png'```
into
```background = 'images/cold-snow-white.jpg'```

And it works. The copy / paste / save via github has no doubt changed something.
Not that it's readible combined with all other default colors ;-)

![image](https://user-images.githubusercontent.com/8142081/51536349-8be60980-1e4b-11e9-8841-603519bc4cf1.png)


One thing I can suggest is look at the size (height x width) of your image and look what the size of the default images is. And adapt your image to that size.  On the other hand.. The image in my /home/pi/PiClock/images directory is 2540 x 1905 and it works...

One last idea (very long shot): could there be a problem with the dashes in the name due to character encoding? rename the file to lowercase letters only e.g. coldsnowwhite.jpg and retry?

OK, ;-) ONE more thing: I just tested with a jpg picture that does NOT exist.
No error message just a black background. An error message would be very nice.

Well enough written to get you busy ;-)

**Comment by feh123** [comment]
No luck so far - tried photo editors to take out EXIF etc, altered name, used smaller photo size.

Could you send the photo back to me - maybe that will work? Thanks!

**Comment by n0bel** [comment]
@ScottChapman @BertLindeman 
So I do love the conversation about changing the text format of the forecast.   Great work and experimentation!   My feeling was that it was "good enough" as is, but lets get it better if we can.

I'm looking seriously about how to incorporate your ideas into the master.

The last method shown here seems to me to show the best promise. https://github.com/n0bel/PiClock/issues/125#issuecomment-456015852

Since the text box size is well defined, I was thinking about an iterative approach where the size is checked with a set of progressively smaller font sizes, and then stopping when it fits.

**Comment by n0bel** [comment]
@feh123 @BertLindeman 

One of the reasons I closed #108 is that open issues that have been resolved tend to go off topic, making it harder for people to find information about the multiple topics within the thread.

It'd be great for you to start a new issue dealing with the background image changes, because this is great information deserving of its own discussion.

**Comment by ScottChapman** [comment]
@n0bel - yea, I agree; I do like the proposed layout and I think it is worth trying.

If it still seems problematic then I'd be happy to put together some "mockup" mechanism for folks to play with and share (on a google doc).

Maybe put the changes on a branch for folks to test before pulling into master?

**Comment by BertLindeman** [comment]
Sorry @n0bel  I do get easily distracted and so items widen.
@feh123 Would you create a new issue like "background image does not show" or something similar?
I have a python script to do some checks on the config. 
Might help. And I could paste your image back to you there.

**Comment by ScottChapman** [comment]
nudge

**Comment by ScottChapman** [comment]
Perhaps someone could just summarize the changes proposed here? I would like to try them out, and if they are good I can create a PR for them.

Thanks!

**Comment by ScottChapman** [comment]
I don't know if that's it or not. I had to take a tape measure to what i was seeing on my screen and I was measuring to the edges of the visible part of the images.

**Comment by BertLindeman** [comment]
May this helps to see some sizes. Added some kind of grid as background:
![image](https://user-images.githubusercontent.com/8142081/51802486-f67fb680-224a-11e9-83fe-21d4a3cbc7f9.png)

**Comment by BertLindeman** [comment]
The grid jpg:

![reggrid_1900x1900](https://user-images.githubusercontent.com/8142081/51802612-15cb1380-224c-11e9-8f8c-187d82661a40.gif)

**Comment by BertLindeman** [comment]
One text layout wish from me I forgot to report.
I use two thermometers on PiClock and their text is overlaying the clock image like this:

![image](https://user-images.githubusercontent.com/8142081/51834945-318df280-22fc-11e9-99e2-4a590d805097.png)

**Comment by xxxDrewedxxx** [comment]
I use this mostly for weather with the clock being secondary.  As such I would like to be able to increase the size of the frames( tiles?) where the weather forecast and radar are.  This would allow more test in a bigger font size.  Is this easily do able?  I've been able to move the radars around in PyQtPiClock, but haven't found what locates and sizes the rest.

**Comment by ScottChapman** [comment]
Any chance we can get these committed? They look like pretty good!

**Comment by n0bel** [comment]
@ScottChapman Get what committed?  There are no pull request regarding things in this thread.

**Comment by ScottChapman** [comment]
Yea, I noticed that. Do the changes seem to be an improvement overall?

**Comment by BertLindeman** [comment]
Will attempt to create a PR for item 1 from n0bel:

> 1 Put all date/time format strings in the config (with appropriate defaults in the startup area so old configs still work)
