### ISSUE TITLE
New install corrupting file system

### ISSUE THREAD

**Issue by cyptex16403** [n0bel/PiClock#129]
On an new PI 3 B, fresh PiClock install with base config, very slow to launch and upon exit file system is corrupted and having to run fsck to recover.  Not sure what could be causing this?  Any Suggestions?

**Comment by billskeen68** [comment]
I updated to the new PiClock2 and now having the same issue.

**Comment by n0bel** [comment]
PiClock2 is not updated to the replacement weather and maps apis.   You need to stick with PiClock, not PiClock2.   As far as things being slow, and the other error you're getting, I'd save your configs to some other computer, then start from scratch with a new SD card.

**Comment by billskeen68** [comment]
Apologies, I updated my comment. I meant the new version using DarkSky.

**Comment by n0bel** [comment]
> 
> 
> I updated to the new PiClock using DarkSky and now having the same issue.
> 
> Also getting this error when ssh in:
> 
> /usr/bin/xauth: error in locking authority file /home/pi/.Xauthority
> 
> Read somewhere it might have to do with being root in pi home directory...looking into setup to see if I missed a step.

This can happen if you run some things as root.   If you're quite familiar with linux, or search alot around the internet you may be able to fix it.    But from my perspective, I'd just start with a new SD card, because that could be the issue anyway.

But really, root should not have been required to update.

**Comment by cyptex16403** [comment]
The new SC recommendations did the trick....thank you all!  It must have been defective from the start...even though it was new as well....no matter....back running as expected....
