### ISSUE TITLE
No Weekly Forecast

### ISSUE THREAD

**Issue by killerkind2134** [n0bel/PiClock#130]
I am using Dark Sky and Mapbox, I set the text files up correctly and yet the clock will still not pull up the weekly forecast or current details in the upper left hand corner. Any help towards a fix for this would be greatly appreciated.

**Comment by killerkind2134** [comment]
Checked logs, and no errors. Fresh install and new update.

**Comment by togatown** [comment]
Look for the lines reading:
```
getting current and forecast:Wed Jan 30 13:22:57 2019
https://api.darksky.net/forecast/yourAPIkey/yourLat,yourLong?units=us&lang=en&r=0.296673988468
```
Are they appearing in your logs?

**Comment by killerkind2134** [comment]
It is now saying "No such file or directory" when attempting to check logs.

**Comment by killerkind2134** [comment]
> Look for the lines reading:
> 
> ```
> getting current and forecast:Wed Jan 30 13:22:57 2019
> https://api.darksky.net/forecast/yourAPIkey/yourLat,yourLong?units=us&lang=en&r=0.296673988468
> ```
> Are they appearing in your logs?

They are appearing in the logs. What else could be wrong?

**Comment by BertLindeman** [comment]
Is this line LITTERALY in your log or are **yourAPIkey/yourLat,yourLong** correctly replaced by **YOUR** values for it?

> getting current and forecast:Wed Jan 30 13:22:57 2019
https://api.darksky.net/forecast/yourAPIkey/yourLat,yourLong?units=us&lang=en&r=0.296673988468

Did you try to copy/paste that line from your log into a browser and did that give an error or did it return a lot of info as a reply?

Mayne paste a link to your complete log might help.
Remove the value of yourAPIkey from the log. 
We do not want to see THAT...

**Comment by n0bel** [comment]
closing as no further activity
