### ISSUE TITLE
Forecast panel hard to read

### ISSUE THREAD

**Issue by ustajan** [n0bel/PiClock#138]
The forecast vertical panel on the right is hard to read...I always get confused between the 3-hourly forecasts and the daily forecasts.  Is it possible to put a thick separator?  Or perhaps remove the boxes around the hourly ones?  

(in case you don't want to change the code for what is mostly an issue of personal taste - can you instead point the place in the code where the boxes are drawn, I can do my own mods.)

**Comment by GrampDamnpus** [comment]
The boxes for the forecast are done with a file located in PiClock/Clock/images/. (squares2-kevin.png ex.) Take one of those into an image editor and make it look however you want. You can edit which boxes are being used, or none for that matter (how I like it). in the Config.py line 15: 
`squares2 = 'images/squares2-kevin.png'` 

If you want to just have no boxes just remove everything so it looks like `squares2 = ''`  Or name it a file that doesnt exist.

**Comment by ustajan** [comment]
Thank you!  I changed the squares to have a clear demarcation between the hourly and daily forecast.

p.s. such a nicely written, modular code...
