### ISSUE TITLE
Weekly Forecasts and Radar does not update

### ISSUE THREAD

**Issue by jdkitzerow** [n0bel/PiClock#139]
I am having trouble with the weekly forecasts and radars updating.  I literally need to shutdown and restart the Pi a couple times before it updates to the current day.  The time on the top middle is correct, just not the weather information until I restart it a couple times.

I even crontab to reboot the pi every day, but its still not updating

Any suggestions?

**Comment by maserowik** [comment]
Do not want to hijack this thread but I have been having the same issue.  

I am running PiClock on a Rapsberry pi zero w.

 

I went back and reload my image 

I  just the Piclock and did not configure any other feature like the led, remote control or the weather probes.

 

So far all has been running without the need to shutdown.

**Comment by jdkitzerow** [comment]
Hijacked!!! Nah, just kidding... Here is a picture of how its Today's date with yesterdays weather....
![piclock](https://user-images.githubusercontent.com/3790477/52496611-b1cc1780-2b88-11e9-9734-cb198288ff21.jpg)

**Comment by n0bel** [comment]
These issues seems like some kind of caching issue.  As if there's a caching proxy between you and the provider.   This might be of help to determine that:   http://www.lagado.com/tools/cache-test
