### ISSUE TITLE
radar map

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#140]
I been looking at the code is there a way to have more than 6 radar images scroll?

**Comment by n0bel** [comment]
In PyQtPiClock.py
```
class Radar(QtGui.QLabel):

    def __init__(self, parent, radar, rect, myname):
        global xscale, yscale
        self.myname = myname
        self.rect = rect
        self.anim = 5
        self.zoom = radar["zoom"]
        self.point = radar["center"]
........
```
The 5 represents the number of frames in the radar animation.   Since RainView provides radar images in 10 minute time frames, this represents 50 minutes of radar images.

**Comment by maserowik** [comment]
Thank you

**Comment by maserowik** [comment]
this can be closed
