### ISSUE TITLE
Russian Cyrillic script not displaying correctly

### ISSUE THREAD

**Issue by RF-Fox** [n0bel/PiClock#153]
Shortly after getting this clock set-up I noticed it cannot display Cyrillic script for whatever reason. Instead of showing the Day of the week it shows non-sense invalid characters. 

![20190329_073433](https://user-images.githubusercontent.com/22880783/55216943-2f48f700-51cc-11e9-8d74-ae0aeefaecf9.jpg)

This is supposed to say "Пятницу, Марта 29th 2019"

**Comment by xenon462** [comment]
in PyQtPiClock.py line 127 add     .decode ('utf-8')
