### ISSUE TITLE
Frame 3

### ISSUE THREAD

**Issue by garry51** [n0bel/PiClock#154]
Can someone help please I have a pi weather station that has been working for about a year now it generates Rrd graphs as png images I would like to show them on frame 3 of my pi clock but alas I no nothing about style sheets so can someone show me how to put 4 png images on frame 3 please.
Thanks

**Comment by togatown** [comment]
Create a label as a sub element of your frame 3:

```
imgcont = QtGui.QLabel(frame3)
imgcont.setObjectName("imgcont")
imgcont.setStyleSheet("imgcont { background-color: transparent; }")
imgcont.setGeometry(0, 0, 720 * xscale, 900 * yscale)
```
Then set the image to appear in the label:

```
myIconMap = QtGui.QPixmap( "pathandfilename.png")
imgcont.setPixmap(myIconMap.scaled(imgcont.size(), Qt.IgnoreAspectRatio, Qt.SmoothTransformation))
```

**Comment by garry51** [comment]
Thanks for the help. I will try it today.

Cheers.


On 6 Apr 2019 5:19 pm, togatown <notifications@github.com> wrote:

Create a label as a sub element of your frame 3:

imgcont = QtGui.QLabel(frame3)
imgcont.setObjectName("imgcont")
imgcont.setStyleSheet("imgcont { background-color: transparent; }")
imgcont.setGeometry(0, 0, 720 * xscale, 900 * yscale)


Then set the image to appear in the label:

myIconMap = QtGui.QPixmap( "pathandfilename.png")
imgcont.setPixmap(myIconMap.scaled(imgcont.size(), Qt.IgnoreAspectRatio, Qt.SmoothTransformation))

**Comment by garry51** [comment]
Thank's it works a treat you have made an old guy very happy.
cherrs Garry

**Comment by garry51** [comment]
The graph image displays ok but alas it wont update. I am sshpassing the image every 5mins to the clock (all working ok) but the clock only displays the image it has on boot up no refresh. Any ideas.

Thanks Garry

**Comment by togatown** [comment]
You'll have to create a routine to update the image every so often or apply it inside one of the existing loops.

**Comment by garry51** [comment]
Its working ok now thanks for the help.
