### ISSUE TITLE
Radar Images have alot of noise

### ISSUE THREAD

**Issue by matg333** [n0bel/PiClock#157]
I am getting alot of noise on the radar images.  The noise looks like theres an old tv screen with static.  Im using the Dark sky and mapbox api's.  Is their anything I can do to clear up the radar images?  Thanks!

**Comment by SerBrynden** [comment]
I see that sometimes, as well.  It's either a problem with the RainViewer.com API, from which the radar image are taken, or a problem with how Qt tiles the images together.  I think it's the first one and you'll have to take the issue to RainViewer.com.  Also, occasionally you'll see circular clumps of noise centered around the radar sites (you can lookup where they are).  This usually occurs on clear days when I think the Weather Service engineers crank up the radar sensitivity, resulting in false returns from low-altitude dust, birds, or moist air near the site.  That's my theory.

**Comment by xenon462** [comment]
This is what they write on https://www.rainviewer.com/help.html

**Comment by n0bel** [comment]
Closing as no further activity

**Comment by SerBrynden** [comment]
See https://github.com/n0bel/PiClock/issues/241#issuecomment-1510003323
