### ISSUE TITLE
Forecast.io

### ISSUE THREAD

**Issue by djevrek** [n0bel/PiClock#16]
Can you consider adding forecast.io as a option for weather data ... much better, with more free "calls" and much more option ... This guy is using it in his project https://github.com/setpixel/weather-display

**Comment by n0bel** [comment]
Yes......  I'll be working on a refactor which separates out the weather/maps out into separate modules.  This will allow the addition of more weather sources.

**Comment by djevrek** [comment]
Great, also consider clock as module, so we can choose digital clock instead of analog

**Comment by n0bel** [comment]
Yes, working on that too.

**Comment by n0bel** [comment]
In that time they became darksky.net.   Implemented in PiClock 2496bbba53d4dd03ee9539ee552d72c43ac7e10d
