### ISSUE TITLE
Radar no longer working

### ISSUE THREAD

**Issue by apparition-** [n0bel/PiClock#171]
Hello everyone. I was experiencing the black rectangles a while back but they stopped without any intervention, however now my radar just no longer displays anything. Just the map part is visible. I noticed yesterday when we had some small storms roll through and I looked at the radar which displayed nothing. Anyone else have this issue before or know where to begin trying to get it back? Thank you in advance.

**Comment by togatown** [comment]
Make a backup of your files and install a fresh copy. Does the issue persist?

**Comment by GrampDamnpus** [comment]
I have the same issue. I will be trying togatowns suggestion, I will report back.

**Comment by togatown** [comment]
@GrampDamnpus Just rename the folder. Are you using ssh or the GUI?

**Comment by GrampDamnpus** [comment]
Well, before I did that I did a git pull update after backing it all up and the radar is working again. The opacity is a little different than it was...but Im not going to complain. So apparition maybe try this https://github.com/n0bel/PiClock/blob/master/Documentation/Install.md#updating-to-newerupdated-versions

**Comment by apparition-** [comment]
> 
> 
> Well, before I did that I did a git pull update after backing it all up and the radar is working again. The opacity is a little different than it was...but Im not going to complain. So apparition maybe try this https://github.com/n0bel/PiClock/blob/master/Documentation/Install.md#updating-to-newerupdated-versions

This worked! Thanks a ton. Really missed having the working radar.
