### ISSUE TITLE
Radar Side By Side

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#173]
Not quite sure what to call the screen so here goes.
1) Form the main PiCLock screen  double click to bring up the side by side radar screen
    On that screen my time stamps on the radar images are not in sequential order.  The time is all 
    over the place.  
2) on the bottom of the screen when it has the date and time mine is still shown in 24 hour time 
    even thought I changed the setting in the PyQtPiClock.py to the {0:%H:%M) to {0:%I:%M %p}  all 
   other places appear to be correctly in 12 hour time.

Thanks

**Comment by togatown** [comment]
Sounds like you may have missed something during the upgrade. Back up the folder or rename it and reinstall. Does that cure it?
