### ISSUE TITLE
PiClock on Buster

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#176]
I had a SD Card failure and redid my Pi-Clock on Buster.  I appear to be having a strange issue.   The screen saver keeps blanking the screen. What is the best way to disable it?

Mike-N3BSQ

**Comment by n0bel** [comment]
These lines in startup.sh should be disabling the screen saver..

...
xset s off
xset -dpms
xset s noblank
...

**Comment by maserowik** [comment]
it is working now

**Comment by maserowik** [comment]
sorry this is now fixed
