### ISSUE TITLE
Modifying the images

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#183]
This may have been addressed before but I can not find it.  

If I wanted to modify the squares and clock face what application do i use to do it.
Are there wiki that I can follow to try to update them>

Thanks 
Mike- N3BSQ

**Comment by feh123** [comment]
Hi I made a new clock face, clock hands etc in a different shape and colour using inkscape - I downloaded a free version. It takes some time to learn how to use it but it works - this helped me: http://write.flossmanuals.net/start-with-inkscape/copying-a-color/. You need to understand the hex colour codes too. So mine was quite a radical change - not sure I am answering your question.
