### ISSUE TITLE
DarkSky no longer accepting new API signups

### ISSUE THREAD

**Issue by SpectrumTech** [n0bel/PiClock#184]
DarkSky is now owned by Apple and no longer allowing new sign-ups. It’s been a year since this project has been updated, so I am assuming it’s dead. Too bad, the Raspi is still going strong with pi4. Any plans to update this?

**Comment by xenon462** [comment]
Developer writes new program code
https://github.com/n0bel/PiClock/issues/179

**Comment by n0bel** [comment]
https://github.com/n0bel/PiClock/issues/179#issuecomment-623172385

**Comment by n0bel** [comment]
Moved to https://github.com/n0bel/PiClock/issues/185
