### ISSUE TITLE
fatal: repository 'https://github.com/n0bel/PiClock.gi/' not found

### ISSUE THREAD

**Issue by ObelI** [n0bel/PiClock#19]
I just follow your guide end:

pi@PiClockKitchen:~ $ git clone https://github.com/n0bel/PiClock.gi
Cloning into 'PiClock.gi'...
Username for 'https://github.com': mr.obeliks@gmail.com
Password for 'https://mr.obeliks@gmail.com@github.com': 
remote: Repository not found.
fatal: repository 'https://github.com/n0bel/PiClock.gi/' not found

**Comment by haxorthematrix** [comment]
The git clone line repository is missing the final t:

git clone https://github.com/n0bel/PiClock.git

From the Get PiClock portion here:https://github.com/n0bel/PiClock/blob/master/Documentation/Install-Clock-Only.md

**Comment by n0bel** [comment]
Yes, thanks haxorthematrix, that's it.
Obell, just do it again with the full repository name.

**Comment by ObelI** [comment]
yep works fine now.

Thank you

**Comment by n0bel** [comment]
great!
