### ISSUE TITLE
Ghosting on radar

### ISSUE THREAD

**Issue by Commander-Crash** [n0bel/PiClock#190]
I don't know if this is a PiClock issue or Radar issue with the API, I am using PiClock on a atomic pi running MX linux 19. I have notice radar glitches and ghosting whear storm passes and it will leave a trail or particals and what looks like lines show up. I do hope this project is still alive I really like this Program.

**Comment by n0bel** [comment]
I've seen this before.  It appears to come from the provider.   Altho in the past I have had issues with certain types of properly formed png files that python or pyqt didn't process correctly.   If you'd like to check yourself, take a look at the log files.  They have the full URL of each radar maptile.  You can copy that URL to your browser, or download with wget/curl and see if you see the problem in the original data.

**Comment by SerBrynden** [comment]
See https://github.com/n0bel/PiClock/issues/241#issuecomment-1510003323
