### ISSUE TITLE
The top line does not display the days of the week with regional settings.

### ISSUE THREAD

**Issue by xenon462** [n0bel/PiClock#206]
![1](https://user-images.githubusercontent.com/34947093/103644090-d98bac00-4f66-11eb-8831-c5a6583535bb.png)

In the PyQtPiClock.py file I added the line
 
ds = ds.decode('utf-8')
ds2 = ds2.decode('utf-8')

![date decode](https://user-images.githubusercontent.com/34947093/103644541-97af3580-4f67-11eb-9b42-5d6e6dd04189.PNG)

The top line worked correctly.
![2](https://user-images.githubusercontent.com/34947093/103644261-23749200-4f67-11eb-8e40-1e8965053b82.png)

![3](https://user-images.githubusercontent.com/34947093/103644274-2a030980-4f67-11eb-91ab-bd701d50ccdb.png)

How do I fix the days of the week in the column on the right?

My settings:
![set](https://user-images.githubusercontent.com/34947093/103644390-59197b00-4f67-11eb-9957-2109907103f5.PNG)

**Comment by xenon462** [comment]
Added "decode ('utf-8')" next to line 909
![decode2](https://user-images.githubusercontent.com/34947093/103670810-22edf280-4f8b-11eb-8076-e35cc3327845.PNG)

The right column only displays the top three rows correctly.
![file5](https://user-images.githubusercontent.com/34947093/103671080-7ceeb800-4f8b-11eb-85aa-3d2451d15c44.png)

The other six days of the week are not displayed.

**Comment by xenon462** [comment]
Made changes on line 976
section  'wxfinished_cc3'

![decode2day](https://user-images.githubusercontent.com/34947093/103676025-a90d3780-4f91-11eb-8627-ff35f0a89535.PNG)

All days of the week work
![file6](https://user-images.githubusercontent.com/34947093/103676154-d0640480-4f91-11eb-9ac7-a78d9ba350b8.png)

How do I ask Kevin to make these fixes to the main code of the program?

**Comment by BertLindeman** [comment]
The procedure would be to edit [Clock/PyQtPiClock.py](https://github.com/n0bel/PiClock/blob/master/Clock/PyQtPiClock.py)
There is a pencil icon near the top on the right side

Edit your changes 
and you should be able to create a pull request.

And then it is up to Kevin to accept or reject.

It's no rocket science but github can be confusing at times.

**Comment by xenon462** [comment]
I can't see a pencil. I will search now. Thanks for the help.

**Comment by ScottChapman** [comment]
You sure you don't see this:
![image](https://user-images.githubusercontent.com/1517892/103681946-2b780600-4f56-11eb-8146-7999dddcaf61.png)
Maybe you aren't logged in?

**Comment by BertLindeman** [comment]
@xenon462 has added #207 for this issue
