### ISSUE TITLE
New feature about music alarm clock

### ISSUE THREAD

**Issue by howardqiao** [n0bel/PiClock#21]
Thank you for a great program!
The clock run perfectly in this thread.
https://www.reddit.com/r/raspberry_pi/comments/4vskrj/piclock_on_raspi_hdtft_hat/
I have an idea:the screen has two gpio buttons,you can add a "musick alarm clock" function to PiClock,one button for music delay,one button for music stop.Are you intrested in the function?

**Comment by n0bel** [comment]
There is already 2 gpio buttons used by the code.. .One to switch screens, the other to play the local audio weather forecast from a noaa stream.

But I'm always interested in seeing patches or pull requests.
