### ISSUE TITLE
Buttons Not Working Under buster

### ISSUE THREAD

**Issue by sschnelker007** [n0bel/PiClock#226]
Has anyone else had a problem with the buttons not working under Buster?  Thx!

**Comment by n0bel** [comment]
I'll be testing this, but I'll be targeting PiOS bullseye over the next week or two.

**Comment by xenon462** [comment]
Buttons must be connected through pull-up resistors
![raspberry-pi-switch-key-right-and-wrong-connection](https://user-images.githubusercontent.com/34947093/145693472-59a65472-076a-4744-b600-e31aa064322a.gif)

**Comment by sschnelker007** [comment]
Thanks, but that didn't work either.  I need to read up on how to test if the Pi sees the button being pressed.

**Comment by sschnelker007** [comment]
> I'll be testing this, but I'll be targeting PiOS bullseye over the next week or two.

Cool, I will keep an eye on this.  It would be nice to get on the latest OS.  8)
