### ISSUE TITLE
ubuntu

### ISSUE THREAD

**Issue by lstew452a** [n0bel/PiClock#235]
Can PiClock work an ubuntu OS?

**Comment by SerBrynden** [comment]
Yes, you can install PiClock on Ubuntu.  I used PyCharm on Ubuntu for my code editing of PiClock.  To use the original PyQt4 version of PiClock, you need Ubuntu 18.04 and install PyQt4 with `sudo apt-get install python-qt4`.  To use the newer PyQt5 version of PiClock, you need Ubuntu 20.04 and install PyQt5 with `sudo apt-get install python3-pyqt5`.  After that, you just need the other prerequisites listed in the PiClock install instructions.
