### ISSUE TITLE
Does it matter what version of qt4 I run in Windows if I am using Python 2.7.12?

### ISSUE THREAD

**Issue by ghart99999** [n0bel/PiClock#24]

**Comment by n0bel** [comment]
I'm guessing no.  Back in may of 2015 I pulled a copy of http://portablepython.com/wiki/Download/  2.7.6 version.  It includes PyQt4 as shown here http://portablepython.com/wiki/PortablePython2.7.6.1/  .  On the windows side, thats all I know about versions.

**Comment by ghart99999** [comment]
Ahh OK. I didn't realize qt4 was included with Python itself. I though it
was a total separate download and install. Thank you.

**Comment by n0bel** [comment]
No, PyQt4 is not included in the normal python download.  Its just included in the one from portablepython.com which I happened to use for myself.

**Comment by ghart99999** [comment]
OK. Just be safe, I will use the portablepython version you used as well.

**Comment by n0bel** [comment]
sounds good
