### ISSUE TITLE
Maps and Radar are showing, nothing else is.

### ISSUE THREAD

**Issue by apparition-** [n0bel/PiClock#245]
Woke up this morning with my PiClock showing the maps, radars and clock just fine but forecast, current info and sunset/sunrise are gone. I am still on the original I believe since it is running on a Pi Zero W. Did SSH and updated and upgraded after noticing the trouble to see if anything changed and nothing did. 

What should I do or check from here?

**Comment by SerBrynden** [comment]
See #185
