### ISSUE TITLE
How to use custom background image?

### ISSUE THREAD

**Issue by ScottChapman** [n0bel/PiClock#25]
I think I figured it out by looking through the code. You want to publish some instructions on how to do that?

I am not sure if the image needs to be a certain size, or if you scale?

**Comment by n0bel** [comment]
I kinda thought the background image was obvious...
In your Config.py
```
background = 'images/clockbackground-kevin.png'
```
The image is automatically scaled.
It could be a jpg too.

When I have a proper skinning system in place, I'll write up the whole thing.

**Comment by ScottChapman** [comment]
Yea, code was pretty simple, just wasn't clear on requirements for image. Thanks!
