### ISSUE TITLE
Not so much an issue as a call for help with crontab

### ISSUE THREAD

**Issue by feh123** [n0bel/PiClock#260]
I have been trying to reboot my PiClock on a schedule with crontab. My code is:

01 19 * * * /sbin/reboot
@reboot sleep 240 && /home/pi/PiClock/startup.sh

If I just reboot the Pi I only get to the Bullseye desktop on my monitor. So this code was my attempt to get the Pi software to re-install and then run startup.sh.

I have tried other variations like adding sh /home/pi/PiClock/startup.sh. I am missing something because the cronjob never works. Any ideas greatly appreciated.

**Comment by SerBrynden** [comment]
Did you try either of these methods: 
https://github.com/n0bel/PiClock/blob/master/Documentation/Install.md#setting-the-clock-to-auto-start

**Comment by SerBrynden** [comment]
Also, per the instructions, the auto-reboot setup should be done as root
`sudo crontab -e`
add the following line
`01 19 * * * /sbin/reboot`

But the PiClock auto-start should NOT root
`crontab -e`
add the following line
`@reboot sh /home/pi/PiClock/startup.sh`

**Comment by feh123** [comment]
And it worked brilliantly. Thanks!

**Comment by SerBrynden** [comment]
Recommend closing this issue.

**Comment by feh123** [comment]
Thanks @SerBrynden
