### ISSUE TITLE
No longer seeing radar images

### ISSUE THREAD

**Issue by ScottChapman** [n0bel/PiClock#270]
For some reason my clock stopped showing radar images. Everything else looks great, but I can't see rain/snow any more!

Any ideas what I should look at first?

**Comment by ScottChapman** [comment]
Got it. HTTPS. Thanks!

**Comment by Knackster** [comment]
Scott,
How did you fix it?

Chris

**Comment by ScottChapman** [comment]
Look at `tileurl` in PyQtPiClock.py, make sure it is HTTPS and not HTTP. It looks like there was a PR that fixed it, so you should be able to just update your clock
