### ISSUE TITLE
Pi Clock Weather Web Display

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#274]
@SerBrynden 

![image](https://github.com/n0bel/PiClock/assets/25713782/163bed72-51c1-4ef5-b9be-b1559c6e1ee7)

How did you get the full USA to display on this?

Mike

**Comment by SerBrynden** [comment]
Adjust the zoom level and coordinates for that particular radar frame in the config file.

**Comment by maserowik** [comment]
do you happend to know what section on the in the code to change.  There a quite a few places in there.


    On Thursday, January 4, 2024 at 10:54:06 AM EST, Brendan Curley ***@***.***> wrote:  
 
 


Adjust the zoom level and coordinates for that particular radar frame in the config file.

**Comment by SerBrynden** [comment]
In your config file: 
```python
radar4 = {
    'center': LatLng(38, -96),
    'zoom': 4,
    'basemap': map_base,
    'overlay': map_overlay,
    'color': 6,
    'smooth': 1,
    'snow': 1,
    'markers': (
        {
            'visible': 0,
            'location': radar_location,
            'color': 'red',
            'size': 'small',
            'image': 'teardrop-dot',
        },
    )
}
```

**Comment by maserowik** [comment]
thanks closing this.
