### ISSUE TITLE
Change URL of one of the radar boxes

### ISSUE THREAD

**Issue by bruster999** [n0bel/PiClock#42]
This is a great project! Well written and easy to install (the software) I am not using buttons or GPIO for anything at the moment but might down the road. I just installed the software on my RPi3 that has a 7" display and it shows me the the weather nicely in a small footprint on my desk. 

My question is, can one of the radar boxes be changed to a different URL? I live on the east coast and would love to have tidal information be displayed. I looked at a few of the .py files but couldn't see how to do that. Is it possible?
Bruster

**Comment by n0bel** [comment]
you'd have to replace the radar2 QFrame and QLabel with your own code.   Its not just a matter of replacing the URL.   The radar frame has 4 stacked labels to show the map, radar and markers with transparency to let them stack.
