### ISSUE TITLE
Can the Daily rainfall be added (Total for the 24 hours)

### ISSUE THREAD

**Issue by n0bel** [n0bel/PiClock#5]
I've had a couple requets for this, so I'll add it somewhere on the display when i get a chance.

**Comment by martymoose** [comment]
Thanks
Where I live in Australia we don't get much rain
So when we do it's a big deal
Cheers

Sent from my android
Check the weather at my house
http://martymandy.com

**Comment by martymoose** [comment]
this is the item i would like added down the track
right hand side of "feels like" look good   Rain 0.0mm
wu  item precip_today_metric
but upto you for where and when
cheers
cheers

**Comment by martymoose** [comment]
any update
Cheers

**Comment by martymoose** [comment]
great work thanks
