### ISSUE TITLE
changing GPIO pins

### ISSUE THREAD

**Issue by nightflasher** [n0bel/PiClock#50]
i really like this project, but i like to add the hardware buttons as well but the gpio pins you're using are already used by my kedei 3.5" (semi-) spi lcd which i like to use.

**Comment by n0bel** [comment]
You can change the GPIO pins as you need.   The specific GPIO pins are specified in startup.sh here:

```
	      echo "Starting gpio-keys Service..."
              sudo Button/gpio-keys 23:KEY_SPACE 24:KEY_F2 25:KEY_UP &
```
