### ISSUE TITLE
Google Map

### ISSUE THREAD

**Issue by jwarrior319** [n0bel/PiClock#53]
Google isnt showing me the correct map its supposed to be Black creek Wi corrdinates 44.4775° N, 88.4507° W
![piclock-1](https://cloud.githubusercontent.com/assets/13908283/22623242/fee50860-eb07-11e6-9074-b358d608b0ab.PNG)
![piclock-2](https://cloud.githubusercontent.com/assets/13908283/22623243/fee81b90-eb07-11e6-97c2-05d1da745c3e.PNG)

**Comment by n0bel** [comment]
West longitude should be entered as a negative number.    You probably didn't put in a "-", so its showing you 44.4775° N, 88.4507° E

**Comment by jwarrior319** [comment]
Thanks, that fixed it
