### ISSUE TITLE
NOAA audio feeds issues

### ISSUE THREAD

**Issue by CigarManDan** [n0bel/PiClock#58]
Is the function for the audio feeds not working for everyone or are some of us doing something wrong?

**Comment by n0bel** [comment]
It works for me.  Check the URL.  Check if it works on your pc.   Check if the player command works..
mpg123 -q http://yourstreamurl  from the command line.

**Comment by n0bel** [comment]
At this point the weather underground noaa feeds seem to be mostly down.   I'm not sure what to do for a replacement.

**Comment by n0bel** [comment]
NOAA weather radio streams have reappeared on the net. You can find it here: http://noaaweatherradio.org/ They don't put the .mp3 urls where they are easily accessable, so you need to use your browser to "View Page Source" in order to find the proper .mp3 url.

**Comment by hsoj95** [comment]
There's still many areas lacking coverage. I live in Georgia, and there's literally no coverage for my state at all. Same for large parts of Florida. I guess there's just some stations that just post their streams online.

**Comment by n0bel** [comment]
As with the weather underground streams, these are private companies or people donating receiving equipment, power and bandwidth to provide this service.  All I can do is provide this information as I come across it.   None of these streams are provided by the government.
