### ISSUE TITLE
weather underground

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#59]
Very nice project.  
I am having a slight configuration issue.

i have my APO for both Google and Weather Underground set up itne the ApiKeys.py
i am getting valid weather output but on the lower left wherne teh wu images are i see the clouds but not the outline of my location
Please look at the attached screen capture.
Thanks
Mike

![piclock-wx](https://cloud.githubusercontent.com/assets/25713782/23755502/92d6ad2a-04ae-11e7-8f39-e8db2ff811a5.PNG)

**Comment by maserowik** [comment]
found the problem.
it was that i did not enable the api in the dashboard.
once done it works.

**Comment by cswanger314** [comment]
How do you enable the API in the dashboard? I am having the same issue. 

Thanks,

**Comment by n0bel** [comment]
Just leave the google API key empty.   As the instructions say, it is not required to make it work, because the volume is so low.
