### ISSUE TITLE
Change Font sizes

### ISSUE THREAD

**Issue by SiriusGen** [n0bel/PiClock#6]
Can the font sizes be changed in a config file? I'd like an option to reduce the text for the forecast down the right hand side. An option to have just the icons would be even better.

**Comment by n0bel** [comment]
The font sizes are hard coded in the main file PyQtPiClock.py, not the config.   They do change based on the screen size (pixels).

**Comment by n0bel** [comment]
Line 741 of PyQtPiClock controls the font size of the forecast boxes, which are the boxes on the right side.

**Comment by n0bel** [comment]
Closing since no more comments.
