### ISSUE TITLE
how do I stop the PiClock and get back to Window?

### ISSUE THREAD

**Issue by VE2DX** [n0bel/PiClock#61]
Sorry newby 

probably simple but ???

once PiClock is up and running? How do I stop it?

I want to put it in auto run but also want to be able to get out of it!

73

RIchard VE2DX

**Comment by n0bel** [comment]
According to the install instructions   "F4 will close the clock"

https://github.com/n0bel/PiClock/blob/master/Documentation/Install.md#first-use

**Comment by kd5pff** [comment]
You can also press ctrl+alt+D to get back to the desktop. This leaves the clock running but let's you do other work on the rPi
