### ISSUE TITLE
IR Remote

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#63]
I have the PiClock up and running for about 1 week now without issues.  I want try to expand and add the ir buttons.

i review the docs 

+### Set up Lirc (IR Remote)
+If you're using the recommended IR Key Fob, 
+https://www.google.com/search?q=Mini+Universal+Infrared+IR+TV+Set+Remote+Control+Keychain

but when I got there it lists all kinds of remotes.  
What is the model the that  most are using?

Thanks

**Comment by n0bel** [comment]
This type:

https://www.amazon.com/HDE-Universal-Stealth-Television-Keychain/dp/B0092TH8WS
