### ISSUE TITLE
question about background

### ISSUE THREAD

**Issue by maserowik** [n0bel/PiClock#68]
What is the max size of the PNG file for the PiClock Background?
I have one that is 2,854 KB and i can not get it to load on the clock
PNG size is 1242 x 2208  is it to big?

Thanks
Mike

**Comment by n0bel** [comment]
There are no limits that I'm aware of.   Check for messages regarding that in the log files (Clock/PyQtPiClock.log)   Also something I kept doing by accident is having something.jpg in the config when it was a something.png or vice versa.
