### ISSUE TITLE
Clone the git

### ISSUE THREAD

**Issue by cwfuselier** [n0bel/PiClock#69]
When I follow he steps to clone the PiCLock it ask for a username & password.

**Comment by n0bel** [comment]
If you miss type any part of the URL that is the response you get.

```
git clone https://github.com/n0bel/PiClock.git
```


I tried for example an incorrect url:
```
[kevinu@cricket2 ~/jjjtest]$ git clone https://github.com/n0bel/PiClick.git
Cloning into 'PiClick'...
Username for 'https://github.com': 
```

So there you go.. check the spelling.. better yet do a copy/paste if you can.

**Comment by cwfuselier** [comment]
ok thanks will try it. Now on the reinstall from fresh the install python-qt4 givea a error when starts to try to download. says 0%[Waitning for headers] then says Connection failed for everything it trys to install. It did the install update fine just this one now.

**Comment by n0bel** [comment]
That message occurs when the Raspberry Pi Repositories are down.   If you try later, it'll probably work.

**Comment by n0bel** [comment]
When this happened to me, i found this post helpful.  https://www.raspberrypi.org/forums/viewtopic.php?f=28&t=126355

**Comment by brandondasdf** [comment]
I really like this project it is very cool. I've been trying to install it a couple times now. 

When I run the 
git clone https://github.com/n0bel/PiClock.git

It loads an then stops at 45%. Any idea why this is happening?

**Comment by n0bel** [comment]
If it does this repeatedly, it is either power or the sd card.    Start with the SD card be sure it is class 10 or uhs.

**Comment by brandondasdf** [comment]
Okay thanks mate I will try that. Could you perhaps elaborate on the class
10? Is that the formatting?

**Comment by n0bel** [comment]
https://www.howtogeek.com/189897/how-to-buy-an-sd-card-speed-classes-sizes-and-capacities-explained/

**Comment by brandondasdf** [comment]
Thank you again
