### ISSUE TITLE
Error in Install guide

### ISSUE THREAD

**Issue by SiriusGen** [n0bel/PiClock#7]
There is an error in the Installation guide here:

https://github.com/n0bel/PiClock/blob/master/Documentation/Install-Clock-Only.md

In the "Configure Your Pi Clock" section it reads:

cp Config-example.py Config.py

However, it should read:

cp Config-Example.py Config.py

The lack of capital E on the word "example" was enough for me not to be able to copy the example file and edit it. Therefore was unable to progress further with the installation. I used File Manager to go into the folder and find the exact file, discovering the capital E on the file and therefore the install worked.

**Comment by n0bel** [comment]
Thanks for pointing this out..   Fixed and merged:  https://github.com/n0bel/PiClock/commit/b2c2b6d36425df987c5c609a44e67527ed851928  Thanks martymoose!
