### ISSUE TITLE
No weekly forecast 

### ISSUE THREAD

**Issue by bigbadmayo** [n0bel/PiClock#80]
I have a satellite image but no radar the weekly forecast is blank. I've tried flashing and reinstalling as well as checking WU's API and lat lon in Config.txt. This Raspberry Pi 2 b is also running Pi-Hole. I have had this set up running before changing from Jessie to Stretch. This is my first issue and I can't wait to get it up and running again. Let me know what files you need!

**Comment by n0bel** [comment]
Check the log files (in the Clock folder) for errors, or other information.  Also included is the url for the forecast and the radar, so you can copy/paste to try in your browser to diagnose.   PyQtPiClock.log is the latest one.

It is most likely an API key, or a lat lon issue.

**Comment by bigbadmayo** [comment]
What is the log file called in Clocks?

**Comment by n0bel** [comment]
PyQtPiClock.log is the latest one.

**Comment by bigbadmayo** [comment]
I have a PyQtPiClock.py but no .log

**Comment by bigbadmayo** [comment]
My brilliant self was using the wrong WU Api.
Thanks for the help!
