### ISSUE TITLE
Would a smooth second hand be possible?

### ISSUE THREAD

**Issue by TQ255** [n0bel/PiClock#87]
Hi everyone,

i'm curious if it would be possible to create a smooth moving second hand like seen in this video:
https://www.youtube.com/watch?v=ArPlKPzOEBM

If i inspect the code it looks like the second hand image rotates by 6 degrees every second. Increasing it to for example rotate 3 degrees every 0.5 seconds would already make it smoother.

**Comment by n0bel** [comment]
It is all going to be dependent on the speed of your Pi.    A possible solution (although still it may be CPU intensive), is to make a gif file, set it up as a frame overlay and run that movie.    Changing the code around line 357 and then around 50 would be where to start.
