### ISSUE TITLE
Updating broke GPIO23 switch?

### ISSUE THREAD

**Issue by Knackster** [n0bel/PiClock#92]
I just updated both of my PiClocks, one of which has a switch on GPIO 23 for screen switching. Since the update, the switch from GPIO 23 to ground no longer switches screens. I've checked startup.sh and all appears to be good. Anyone have any thoughts?

Thanks,

Chris

**Comment by dankolbrs** [comment]
Did you get it to work?

Was the upgrade to the PiClock^2'd version? I don't use GPIO pins with PiClock so I probably can't be much help here. The update instructions include removing and re-making the gpio-keys, was that step included? 
```
Also, if you're using gpio-keys, you may need to remake it:

cd PiClock/Buttons
rm gpio-keys
make gpio-keys
```

If it still doesn't work, may need to step through the installation instructions relevant to the GPIO keys to reconfigure. Sorry I can't be more helpful, but I'd be interested in hearing the outcome.
