### ISSUE TITLE
Lack of Comments in PyQtPiClock.py

### ISSUE THREAD

**Issue by alphamobius** [n0bel/PiClock#99]
I'd love to help work on this, particularly on the gps-based lat/long updates, and modifying the UI just a little bit for my needs, however the lack of comments in the main file are really slowing me down....

The comments in the readme, instructions, Config.py, and ApiKeys.py are great, but are desperately needed in the main file.  Right now it's over 1000 lines of uncommented mystery, and you would attract a lot more help in the project if it wasn't so daunting to get started. Thanks in advance!

**Comment by dankolbrs** [comment]
Adding comments could be a good way to get to know the code and get started in contribution ;)

@n0bel , you got a `low hanging fruit` kind of label fitting for this?
